### ISSUE TITLE
Error: Cannot find module '../Errors/RedisError'

### ISSUE THREAD

**Issue by serak** [ctoesca/redjs#18]
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../Errors/RedisError'
Require stack:
- C:\Users\Serak\Desktop\node_embedded\node_modules\Redjs\dist\Data\Datastore.js
- C:\Users\Serak\Desktop\node_embedded\node_modules\Redjs\dist\RedjsServer.js
- C:\Users\Serak\Desktop\node_embedded\node_modules\Redjs\dist\index.js
- C:\Users\Serak\Desktop\node_embedded\embedded_redis.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\Serak\Desktop\node_embedded\node_modules\←[4mRedjs←[24m\dist\Data\Datastore.js:8:22)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Serak\\Desktop\\node_embedded\\node_modules\\Redjs\\dist\\Data\\Datastore.js'←[39m,
    ←[32m'C:\\Users\\Serak\\Desktop\\node_embedded\\node_modules\\Redjs\\dist\\RedjsServer.js'←[39m,
    ←[32m'C:\\Users\\Serak\\Desktop\\node_embedded\\node_modules\\Redjs\\dist\\index.js'←[39m,
    ←[32m'C:\\Users\\Serak\\Desktop\\node_embedded\\embedded_redis.js'←[39m
  ]
}
```

**Comment by im-calvin** [comment]
I'm having the same issue, any advice?
